### PR TITLE
Removing dependency on onEnterKeyDown and using onKeyDown as per material-ui request (onEnterKeyDown deprecated)

### LINKED ISSUE #60: onEnterKeyDown has been deprecated in material-ui 0.15
material-ui has released an alpha of 0.15 where onEnterKeyDown has been deprecated.
This causes a warning in the console:
```
Warning: "onEnterKeyDown" property of "TextField" has been deprecated.
Use onKeyDown and check for keycode instead.
```

### PR DESCRIPTION
**Pull request by enricofoschi**
Closes #60

### CODE REVIEW

**Comment by kainolophobia** [comment]
:+1:

**Comment by mbrookes** [comment]
@kainolophobia :+1: 

image

**Comment by kainolophobia** [comment]
What can we do to help merge this?

**Comment by mbrookes** [comment]
Sorry @kainolophobia, I've been focussed on the Material-UI 0.15.0-alpha.2 release. I'll look at this soon.

**Comment by simpixelated** [comment]
Should fix #71.

**Comment by duylam** [comment]
Hope this PR to be merged

**Comment by mbrookes** [comment]
Funny you should ask (was that a verbal '+1' ? :smile: ) as I started updating this about 5 minutes before your comment.

**Comment by keremciu** [comment]
do you have any estimate to finish that update? @mbrookes I'm so excited about this repository, if you have any roadmap maybe we can help for something? 🤓

**Pull request merged**
