### PR TITLE
Revert #174 and re-apply interim changes

### PR DESCRIPTION
**Pull request by rojobuffalo**
@codeaholicguy hey, would you mind giving this a quick review?

### CODE REVIEW

**Comment by codeaholicguy** [comment]
LGTM

**Comment by codeaholicguy** [comment]
@rojobuffalo Should fix linter before merging

**Comment by rojobuffalo** [comment]
It's a false positive from the linter: see [related issue](https://github.com/eslint/eslint/issues/7297). A comma after `...rest` is a syntax error, so our eslint rule `comma-dangle: ["error", "always-multiline"]` is supposed to allow there not to be a comma in this special case.

I see 3 options:
1. Let it through with an error reporting a false positive.
2. Try upgrading babel-eslint.
3. Temporarily disable the eslint rule or inline disable

**Comment by codeaholicguy** [comment]
I think update `.eslintrc` is the best way to do this

**Comment by rojobuffalo** [comment]
Turns out putting the `} = this.props` on the same line with `...rest` silences the error. This is sort of letting the tail wag the dog, but whatever.

**Pull request merged**
