### PR TITLE
Changes in v0.2.3 was a mistake. This commit fixes that by using the …

### PR DESCRIPTION
**Pull request by vijayrawatsan**
…approach explained on https://github.com/christianalfoni/formsy-react/wiki/validate-on-blur.

### CODE REVIEW

**Comment by mbrookes** [comment]
This looks like a much more comprehensive approach, thanks. I don't have time to test right it now, but if you do, could you check how this behaves with textfields that are required, but don't have a validation rule, ref @dmlinn's comment here: https://github.com/mbrookes/formsy-material-ui/issues/6 ?

**Comment by vijayrawatsan** [comment]
@mbrookes This solution is so elegant that it fixes https://github.com/mbrookes/formsy-material-ui/issues/6 
Again thanks to https://github.com/christianalfoni/formsy-react/wiki/validate-on-blur 
@mvandiest @dmlinn Can you also give it a try. May be I m missing something.

**Comment by vijayrawatsan** [comment]
@mbrookes merging. I will also push a tag 0.2.4.

**Comment by vijayrawatsan** [comment]
Tag 0.2.4 pushed. Please update it on npm. Current latest on npm is too buggy to be used. :+1: 
Thanks

**Comment by mbrookes** [comment]
Pleas update the README and packages.json before pushing a new tag.

**Comment by mbrookes** [comment]
> This solution is so elegant that it fixes #6 

Sadly no. The crux of #6 is that validating onBlur means the submit button doesn't get enabled if the last field is a textfield. This doesn't fix that, I think only an option for when to validate each (onChange vs onBlur) will.

I'm going to publish on the basis that it fixes what your last PR broke, but if it transpires it causes more problems that it fixes, or makes addressing #6 more challenging, we may need to revert to 0.2.2 and go from there.

**Comment by mbrookes** [comment]
Your code won't transpile. Looks like you've copied some (incomplete) transpiled code back into formsy-material-ui.jsx? I've had to revert. Please review your code and resubmit. Thanks,

**Pull request merged**
