### PR TITLE
Add prop updateImmediately to FormsyText

### PR DESCRIPTION
**Pull request by codeaholicguy**
I added prop `updateImmediately` to `FormsyText` in case someone want to get status valid or invalid of textbox immediately when user fill in.

**Usage**
```jsx
<FormsyText
  name='name'
  updateImmediately
/>
```

### CODE REVIEW

**Comment by krizka** [comment]
Updating on every change is slow for text inputs. Need to add some debouncing here.

**Comment by codeaholicguy** [comment]
@krizka good idea

**Comment by krizka** [comment]
Please, look at my gist in comments to #97

**Comment by codeaholicguy** [comment]
@krizka Nice, I added debounce for solving performance issue when setValue continuously

**Comment by krizka** [comment]
I think, you made it wrong. We can not call debounce every time we want to change, but have to get a function from debounce and call it many times. That is why I making setValidate method only once on component mount.

**Comment by codeaholicguy** [comment]
that why I created `this.changeValue`

```jsx
if (this.props.updateImmediately) {
  if (this.changeValue) {
    this.changeValue(event.currentTarget.value);
  } else {
    this.changeValue = debounce(this.setValue, 200);
    this.changeValue(event.currentTarget.value);
  }
}
```

**Comment by krizka** [comment]
Oh, sorry, now I got it. Nice job)
To be more clear and dry, maybe.
```
if (!this.changeValue)
  this.changeValue = debounce(this.setValue, 200);

this.changeValue(event.currentTarget.value);
```

**Comment by codeaholicguy** [comment]
great, thank you for you feedback

**Comment by mbrookes** [comment]
Please check out #109.

**Pull request merged**
