### PR TITLE
fix #177 unknown props on autocomplete

### LINKED ISSUE #177: AutoComplete unknown props `validationError`, `validationErrors`
Hi, this code produces the following error : 

> Warning: Unknown props `validationError`, `validationErrors` on <input> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
>     in input (created by TextField)
>     in div (created by TextField)
>     in TextField (created by AutoComplete)

```
<FormsyAutoComplete
	name='userId'
	floatingLabelText="How often do you?"
	dataSource={this.state.users}
	dataSourceConfig={sourceConfig}
/>
```

I tried with AutoComplete from material-ui, it works fine

### PR DESCRIPTION
**Pull request by nicgirault**
Hello @mbrookes, could you merge this fix?

Thanks

### CODE REVIEW

**Comment by rojobuffalo** [comment]
This looks good except for the package maintenance changes. Please re-submit with just the fix. I'll publish a new version with a batch of changes this week.

**Comment by nicgirault** [comment]
@rojobuffalo done

**Comment by rojobuffalo** [comment]
Thanks, but it looks like there is still a `package-lock` file committed. I don't think we want that in the repo.

**Comment by nicgirault** [comment]
@rojobuffalo oups sorry, I was reading too quickly the pull request

**Pull request merged**
