### PR TITLE
Update version for material-ui v0.16 in peerDepencencies

### PR DESCRIPTION
**Pull request by joelkoz**
Material-UI version is required in both peerDependencies and
devDependencies.

### CODE REVIEW

**Comment by rojobuffalo** [comment]
The integration test failed. How can we make it pass? Does material-ui need to be included in both `peerDependecies` and `devDependencies`?

**Comment by joelkoz** [comment]
The test fails on the current 0.5.2 release also. The PR that fixes the validation issue needs to be applied also to get it to pass. 

-jk
(sent from my iPhone)

**Comment by joelkoz** [comment]
Re: being in peerDependencies AND devDependencies: I don't know if it needs to be in both places or not, but the current 0.5.2 release has them in both places, so I didn't think I should change that.

**Comment by crashbell** [comment]
Thank you @joelkoz @rojobuffalo 
I hope that this change can be published soon since we are stuck upgrading `material-ui` due to peerDep.

**Comment by rojobuffalo** [comment]
As mentioned in #152, if you pull down the HEAD of the master branch and confirm that everything is working--I'm happy to publish v0.5.3. I think it's ready, but just want some confirmation.

**Pull request merged**
