### PR TITLE
Fixed controlled Date and TimePicker value update

### PR DESCRIPTION
**Pull request by ferencrocks**
Possible fix for issue #180

### CODE REVIEW

**Comment by rojobuffalo** [comment]
@ferencrocks Hey can you squash those commits please?

**Comment by mbrookes** [comment]
@rojobuffalo Thanks for picking up the open issues and PRs! That reminded me to ask - would you like me to transfer the repo to you, or create its own org? Seems a little unfair that it still appears to be mine when you're doing all the work these days.

On this one, there's now the option to squash and merge (drop-down icon on merge button), so you don't have to wait for  @ferencrocks to do it.

**Comment by rojobuffalo** [comment]
Cool, thanks for pointing out that feature. I'm ok with you transferring the repo but I don't mind either way.

**Comment by mbrookes** [comment]
I'm happy for you to take it. I tried transferring it, but I think you'll need to delete your fork first, so let me know when that's done, and I'll give it another go.

**Comment by rojobuffalo** [comment]
Ok. I just renamed my fork.

**Comment by mbrookes** [comment]
Now I get a different error 🤦‍♂️ 
"rojobuffalo already has a repository in the mbrookes/formsy-material-ui network"

Looks like you'll have to delete your fork, sorry.

**Comment by rojobuffalo** [comment]
Ok, I deleted it.

**Comment by mbrookes** [comment]
"You have the bridge."

**Comment by rojobuffalo** [comment]
Captain

**Comment by rojobuffalo** [comment]
Thanks @mbrookes

**Pull request merged**
