### PR TITLE
Fixes React 15.2 unknown props warnings. Closes #119.

### LINKED ISSUE #119: React 15.2 issues warnings for unknown props.
I'm preparing a pull request to fix this, but seeing as I'm not using all the different input types in my app that formsy-material-ui supports, it could probably use some additional testers.

### PR DESCRIPTION
**Pull request by jayalfredprufrock**

### CODE REVIEW

**Comment by sgabler** [comment]
Very nice! I tested your changes in my current project, and the console warnings went away. So far everything looks good. I'd maybe squash down your pull request so you don't have this reverted commit, but apart from that it looks good to me 👍 

@mbrookes: What do you think about creating a new npm release after merging in this pull request? Then people can update to the latest react without drowning in console warnings 😉

**Comment by mbrookes** [comment]
@sgabler Thanks for testing this. @jayalfredprufrock Yes, please squash or drop the last two commits.

**Comment by sgabler** [comment]
@mbrookes: I just realized I was not specific enough earlier. My current project only uses two components at the moment: FormsyText and FormsySelect. I have not tested the other options.

**Comment by yonidej** [comment]
Worked perfectly for most of the components. I still get the following errors:
`Unknown prop `menuItems` on <div> tag`
`Unknown props `validations`, `validationError`, `validationErrors` on <input> tag`
`Unknown prop `onTouchTap` on <label> tag`

**Comment by jayalfredprufrock** [comment]
Alrighty, I'll squash down the PR and see if I can test out the other inputs as well. @yonidej the 'menuItems' and 'onTouchTap' props aren't really a part of formsy so the responsibility of fixing those probably lies elsewhere. I'll investigate the others.

**Comment by jayalfredprufrock** [comment]
The remaining warnings @yonidej mentioned were from FormsyRadioGroup and required a bit of a different approach to fix. The latest squashed commit fixes those as well. I tested all input types using the example form in this repo and everything seems to check out.

**Comment by sgabler** [comment]
Looks good to me. Do we need some additional checks or tests before this could be merged @mbrookes ?

**Comment by jayalfredprufrock** [comment]
I'd really love to see this get merged this week. @mbrookes do let me know if there is anything else I can do.

**Comment by mbrookes** [comment]
@jayalfredprufrock Thanks for taking care of this.

**Comment by DrkCoater** [comment]
thanks!

**Comment by ddela-cr** [comment]
Im still having this error on 0.5.3, react 15.4.0

> Unknown props `validations`, `validationError`, `validationErrors` on <input> tag

**Comment by rojobuffalo** [comment]
@ddela-cr which component?

**Comment by ddela-cr** [comment]
@rojobuffalo Autocomplete component, i opened an issue few days ago. Please check #177

**Pull request merged**
