### PR TITLE
Fix this.handleEnterKeyDown bug on 0.4.0

### PR DESCRIPTION
**Pull request by quangdng**
Hi guys,

This is my very quick fix for this issue. Feel free to correct me.

Thanks.

### CODE REVIEW

**Comment by reebalazs** [comment]
I've tested it and the fix works for me.

(Only, I cannot use this branch directly, as the libs need to be rebuilt. I did that manually, and all seems good so far.)

**Comment by jackyon** [comment]
+1 waiting for the new release.

**Comment by reebalazs** [comment]
Actually after making my previous comment, I realized that this is already fixed on master, which makes the 5.x branch and this patch unneeded. This way I believe that this PR can be closed.

**Comment by quangdng** [comment]
Close pull request as the bug is fixed on 0.4.1

**Pull request closed without merging**
