### PR TITLE
set up unit-testing tools

### PR DESCRIPTION
**Pull request by py-in-the-sky**
Also write a few unit tests to get things started.

### CODE REVIEW

**Comment by py-in-the-sky** [comment]
@mbrookes If I got things set up right, you should be able to checkout this branch and run `npm install && npm test` without any errors.  I just wanted to get some tools set up for testing.  I figure we can fill out the test suite over time.  The formsy-react repo has many great tests that we can model ours after.

**Comment by mbrookes** [comment]
Thanks for this. :+1: 

I just upgraded babel. Could you rebase please?

**Comment by mbrookes** [comment]
Also, some interesting discussion here. We're never going to have performance problems with this small set of components, but just for reference: https://github.com/callemall/material-ui/issues/3241#issuecomment-181957671

**Comment by py-in-the-sky** [comment]
I rebased.  The latest uses Karma, which both material-ui and formsy-react use.  There are some things that just can't be tested outside an actual browser right now.

Regarding shallow rendering, I haven't looked into this enough to fully understand why, but tests involving formsy don't work without full rendering.  The [React docs](https://facebook.github.io/react/docs/test-utils.html#shallow-rendering) provide only a short review of some limitations of shallow rendering.

**Comment by mbrookes** [comment]
Love it!

Thank you for getting this up and running!!!

**Pull request merged**
