### PR TITLE
Allow onChange event to propagate up.

### PR DESCRIPTION
**Pull request by magicalcows**
I need the new value from the select to change something on the page in real time, without actually saving, so I needed to tap into the onChange event.  You might consider adding this to the other components as well. (Or I will as needed. ;)

Awesome repo BTW. MOO! =)

### CODE REVIEW

**Comment by mbrookes** [comment]
Thanks for the PR. 

The only issue I see is that the callback property order is [set to be changed](https://github.com/callemall/material-ui/issues/2957) in Material-UI, so it might make sense to adopt the proposed order from the outset. It would reduce the impact when that change happens on the Material-UI side.

What do you think?

**Comment by magicalcows** [comment]
I totally agree. I'd love to adopt that now, it'll save me some trouble down the lilne ;)

What's the new order going to be?

**Comment by magicalcows** [comment]
My bad, I didn't notice the link in your comment at first. ;)

I'll submit a new PR in a bit!

**Comment by mbrookes** [comment]
Great! :+1:

**Comment by magicalcows** [comment]
closing in favor of https://github.com/mbrookes/formsy-material-ui/pull/49

**Pull request closed without merging**
