### PR TITLE
Update to React 15 and Material UI 0.15

### PR DESCRIPTION
**Pull request by enricofoschi**
This is based on recent changes on master + mui0150 branch.

Includes a few fixes (controlled vs uncontrolled components) and it could be a starting discussion point to update this repository to work with the new versions.

### CODE REVIEW

**Comment by enricofoschi** [comment]
I also removed the "lib" folder, mainly because I'd like to use this repo from npm directly without publishing it to a new module.

**Comment by mbrookes** [comment]
Thanks, but I can't use this. If there is a specific issue you'd like to fix please open a PR for it, without the content of the mui-0150 branch, or the other random noise.

**Comment by enricofoschi** [comment]
Hi @mbrookes - thanks for getting back on this. Do you already have a plan for migrating to 15?

Are you specifically asking to create smaller / specific pr to the mui-0150 branch?

**Comment by keremciu** [comment]
@mbrookes do you have any plan for this repository?

**Pull request closed without merging**
